### ISSUE TITLE
Uncaught TypeError: _victoryUtil.Collection.allEqual is not a function

### ISSUE THREAD

**Issue by nikolay-g** [FormidableLabs/victory#532]
I'm using candle chart and getting the following error:

```
Uncaught TypeError: _victoryUtil.Collection.allEqual is not a function
    at Candle.shouldComponentUpdate (candle.js:44)
    at ReactCompositeComponent.js:625
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:624)
    at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
    at Object.receiveComponent (ReactReconciler.js:125)
    at Object.updateChildren (ReactChildReconciler.js:109)
    at ReactDOMComponent._reconcilerUpdateChildren (ReactMultiChild.js:208)
    at ReactDOMComponent._updateChildren (ReactMultiChild.js:312)
    at ReactDOMComponent.updateChildren (ReactMultiChild.js:299)
    at ReactDOMComponent._updateDOMChildren (ReactDOMComponent.js:936)
```

Indeed, I checked for a method `allEqual` in Victory core and couldn't find any ...

Any ideas how to work around this?

**Comment by DerekMaffett** [comment]
Internal error. Fixing it now

**Comment by nikolay-g** [comment]
When will the next NPM version of Victory be released? I'm currently working with `"0.17.0"` to bypass the issue.
