### ISSUE TITLE
Typescript builds fail on version 36.2.1

### ISSUE THREAD

**Issue by Tyresius92** [FormidableLabs/victory#2084]
# Bugs and Questions

### Checklist

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Our TypeScript build is failing when upgrading from 36.2.0 to 36.2.1 due to missing types. We believe the issue was introduced in https://github.com/FormidableLabs/victory/pull/2058

The error message output is: 

```sh
> tsc --project ./tsconfig.build.json --outDir ./dist

node_modules/victory/lib/index.d.ts:114:5 - error TS2305: Module '"victory-selection-container"' has no exported member 'SelectionHelpers'.

114     SelectionHelpers,
        ~~~~~~~~~~~~~~~~

node_modules/victory/lib/index.d.ts:115:5 - error TS2305: Module '"victory-selection-container"' has no exported member 'selectionContainerMixin'.

115     selectionContainerMixin
        ~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

### Reproduction

I've created a minimal reproduction here: https://github.com/Tyresius92/victory-bug-reproduction

Alternatively, you can create a reproduction of the issue by: 
1. Create a new React application with `npx create-react-app my-app --template typescript`
2. Update `skipLibCheck` to false in `tsconfig.json`
3. Update the `build` command in `package.json` to `tsc --outDir ./dist`
4. Run `npm run build`

**Comment by becca-bailey** [comment]
Thanks for letting me know! This is probably related to #2058.

**Comment by kaiyoma** [comment]
Same problem here. Type checking fails in my project now after upgrading to 36.2.1.

**Comment by becca-bailey** [comment]
I'm looking into this today. There might be a quick fix, otherwise I will just revert 2058.

**Comment by jasherman** [comment]
@becca-bailey Any update on resolving this?

**Comment by becca-bailey** [comment]
#2058 Has been reverted, and I just published `v36.2.2`. Pulling the latest version should resolve this issue.
